### ISSUE TITLE
Pluto - Telemetry Primitive Refactoring

### ISSUE THREAD

**Issue by emilbon99** [synnaxlabs/synnax#448]
Checklist:

- [ ] P&ID Tooltips
- [ ] Better edge movement
- [ ] Consistent value positioning
- [ ] Edge alignment
- [ ] Consistent path widths
- [ ] Performance improvements and smoother movement
- [ ] Clean up orientation dialog and make more semantic.
- [ ] Only label orientation control
- [ ] Tooltips
- [ ] Closer attachment on edges
- [ ] Undo + redo
